import { useState } from 'react'
import { CheckCircle, XCircle, AlertTriangle, Clock, Edit3 } from 'lucide-react'
import type { Ticket } from '../tickets/KanbanBoard'

interface HitlConsoleProps {
    ticket: Ticket | null
}

const mockAiAnswer = `Based on the submitted query regarding the procurement regulation amendment, the following analysis has been generated by the AI knowledge system:

**Regulatory Context:**
Under Jordan's Public Procurement Law No. 32 of 2009, as amended by Law No. 24 of 2012, the entity must adhere to the following thresholds for direct purchase: JD 1,000 for goods and JD 2,000 for services.

**Policy Recommendation:**
The proposed amendment falls within the jurisdictional authority of the Higher Procurement Committee. We recommend forwarding this request to the relevant ministry with a full compliance checklist.

**Cited Sources:**
1. Public Procurement Law No. 32/2009, Article 14, Section (B)
2. Cabinet Decision No. 8881 of 2020
3. Anti-Corruption Commission Circular 2023-07`

export default function HitlConsole({ ticket }: HitlConsoleProps) {
    const [editedAnswer, setEditedAnswer] = useState(mockAiAnswer)
    const [decision, setDecision] = useState<'approved' | 'rejected' | null>(null)
    const [feedback, setFeedback] = useState('')

    if (!ticket) {
        return (
            <div className="flex flex-col items-center justify-center h-64 text-center">
                <Edit3 size={32} className="text-slate-700 mb-3" />
                <p className="text-slate-600 text-sm font-medium">No ticket selected</p>
                <p className="text-slate-700 text-xs mt-1">Click a "Pending HITL" card from the Kanban board</p>
            </div>
        )
    }

    const handleApprove = () => setDecision('approved')
    const handleReject = () => setDecision('rejected')

    return (
        <div className="flex flex-col gap-4">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-white font-bold text-base">Human Review Console</h2>
                    <p className="text-slate-500 text-xs mt-0.5">
                        Reviewing AI response for <span className="text-blue-400 font-mono">{ticket.id}</span>
                    </p>
                </div>
                {decision && (
                    <div className={`flex items-center gap-2 px-3 py-1.5 rounded-lg border text-xs font-semibold
            ${decision === 'approved'
                            ? 'bg-emerald-500/15 border-emerald-500/30 text-emerald-400'
                            : 'bg-red-500/15 border-red-500/30 text-red-400'}`}>
                        {decision === 'approved' ? <CheckCircle size={13} /> : <XCircle size={13} />}
                        {decision === 'approved' ? 'Approved & Dispatched' : 'Rejected — Pending Revision'}
                    </div>
                )}
            </div>

            {/* SLA warning banner */}
            <div className="flex items-center gap-2 px-4 py-2.5 bg-amber-500/10 border border-amber-500/20 rounded-lg">
                <AlertTriangle size={13} className="text-amber-400 shrink-0" />
                <span className="text-amber-300 text-xs font-medium">
                    SLA deadline approaching. Please review and act within the allotted time window.
                </span>
                <div className="flex items-center gap-1 ml-auto text-amber-500 text-[10px] font-mono shrink-0">
                    <Clock size={10} />
                    42m 18s
                </div>
            </div>

            {/* Split-screen workspace */}
            <div className="grid grid-cols-2 gap-4">
                {/* LEFT: User Query */}
                <div className="flex flex-col bg-[#0c1424] border border-slate-700/50 rounded-xl overflow-hidden">
                    <div className="px-4 py-3 border-b border-slate-700/40 flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-blue-500" />
                        <h3 className="text-slate-300 text-xs font-semibold uppercase tracking-wider">User Query</h3>
                        <span className="ml-auto text-slate-600 text-[10px] font-mono">{ticket.sector}</span>
                    </div>
                    <div className="p-5 flex-1">
                        <div className="flex items-start gap-3 mb-4">
                            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-slate-600 to-slate-700 flex items-center justify-center text-white text-xs font-bold shrink-0">
                                U
                            </div>
                            <div className="flex-1">
                                <p className="text-slate-200 text-sm font-semibold mb-1">{ticket.title}</p>
                                <p className="text-slate-500 text-[10px]">Submitted via Public Portal · {ticket.sector}</p>
                            </div>
                        </div>
                        <div className="bg-slate-800/40 rounded-lg p-4 border border-slate-700/40">
                            <p className="text-slate-300 text-xs leading-relaxed">
                                We are seeking clarification on the applicability of the recent amendment to Article 14
                                of the Procurement Law with respect to our direct purchase authority ceiling. Our annual
                                budget cycle begins next quarter and we need authoritative guidance on whether the
                                JD 1,000 threshold applies to framework agreements or only spot purchases. Could you
                                provide a formal policy interpretation with applicable legal citations?
                            </p>
                        </div>
                        <div className="mt-3 flex flex-wrap gap-1.5">
                            {ticket.tags.map((tag) => (
                                <span
                                    key={tag}
                                    className="px-2 py-0.5 rounded text-[9px] font-medium bg-slate-700/60 text-slate-400 border border-slate-600/40"
                                >
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                {/* RIGHT: AI Answer Editor */}
                <div className="flex flex-col bg-[#0c1424] border border-slate-700/50 rounded-xl overflow-hidden">
                    <div className="px-4 py-3 border-b border-slate-700/40 flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-purple-500" />
                        <h3 className="text-slate-300 text-xs font-semibold uppercase tracking-wider">AI-Generated Response</h3>
                        <span className="ml-auto text-slate-600 text-[10px]">Edit before approving</span>
                    </div>
                    <div className="p-4 flex-1 flex flex-col gap-3">
                        <textarea
                            value={editedAnswer}
                            onChange={(e) => setEditedAnswer(e.target.value)}
                            disabled={!!decision}
                            className="flex-1 w-full min-h-56 bg-slate-900/60 border border-slate-700/40 rounded-lg px-4 py-3
                         text-slate-300 text-xs leading-relaxed font-mono resize-none
                         focus:outline-none focus:border-blue-500/50 focus:bg-slate-900
                         disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                        />

                        {/* Reviewer feedback */}
                        <input
                            type="text"
                            value={feedback}
                            onChange={(e) => setFeedback(e.target.value)}
                            disabled={!!decision}
                            placeholder="Add reviewer note (optional)…"
                            className="w-full px-3 py-2 bg-slate-800/50 border border-slate-700/40 rounded-lg text-xs text-slate-300
                         placeholder-slate-600 focus:outline-none focus:border-blue-500/50 disabled:opacity-50 transition-all"
                        />
                    </div>
                </div>
            </div>

            {/* Action buttons */}
            {!decision && (
                <div className="flex items-center justify-end gap-3 pt-1">
                    <button
                        onClick={handleReject}
                        className="flex items-center gap-2 px-5 py-2.5 rounded-lg border border-red-500/30 text-red-400 text-sm font-semibold
                       hover:bg-red-500/15 transition-all"
                    >
                        <XCircle size={15} />
                        Reject & Flag
                    </button>
                    <button
                        onClick={handleApprove}
                        className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-emerald-600 text-white text-sm font-semibold
                       hover:bg-emerald-500 shadow-lg shadow-emerald-900/40 transition-all"
                    >
                        <CheckCircle size={15} />
                        Approve & Dispatch
                    </button>
                </div>
            )}
        </div>
    )
}
